### ISSUE TITLE
Bring website into agreement with PDF version of the document

### ISSUE THREAD

**Issue by twjordan** [twjordan/PBD-Guide-for-PRN#5]
We had a round of editing for the PBD handbook that occurred after the website was published, but before the PDF was created. There are a variety of edits, some typographical in nature and some more substantial -- there is an entire sub-section missing from the website, in fact.

For source materials we have a word document with tracked changes (available via email) and the finished printable PDF version of the handbook.
[Parking Benefits District Digital Guide.pdf](https://github.com/ParkingReformNetwork/PBD-Guide-Website/files/12147774/Parking.Benefits.District.Digital.Guide.pdf)

**Comment by sulllyy** [comment]
Done

**Comment by twjordan** [comment]
Awesome.
